version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=repsy-api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  repsy-app:
    image: repsy-app:1.0.0
    container_name: repsy-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      - STORAGE_STRATEGY=file-system
      - STORAGE_FS_PATH=/var/data
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/repsy-api
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres_db
    volumes:
      - repsy_fs:/var/data

volumes:
  postgres_db:
    driver: local
  repsy_fs:
    driver: local
