version: '3.8'

services:
  repsy-app:
    image: repsy-app:1.0.0
    container_name: repsy-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=file-system
      - STORAGE_FS_PATH=/var/data
    volumes:
      - repsy_fs:/var/data

volumes:
  repsy_fs:
    driver: local
